kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: irlogs
  annotations:
    volume.beta.kubernetes.io/storage-class: azurefile
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: instarent-payment-deployment
  labels:
    app: instarent-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: instarent-payment
  template:
    metadata:
      labels:
        app: instarent-payment
    spec:
      containers:
      - name: paymentservice
        image: instarent.azurecr.io/instarentpayment:latest
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        env:
        - name: ASPNETCORE_URLS
          value: "https://+;http://+"
        - name: ASPNETCORE_Kestrel__Certificates__Default__Password
          valueFrom: 
            secretKeyRef:
              name: instranet-app-secret
              key: ASPNETCORE_Kestrel__Certificates__Default__Password
        - name: ASPNETCORE_Kestrel__Certificates__Default__Path
          value: "/dev-cert/localhost.pfx"
        - name: App__SelfUrl
          value: "https://payment.instarentbag.com"
        - name: App__CorsOrigins
          value: "https://webgateway-service,http://webgateway-service,https://webgateway.instarentbag.com,http://webgateway.instarentbag.com"
        - name: ConnectionStrings__InstaRent 
          valueFrom: 
            secretKeyRef:
              name: instranet-app-secret
              key: ConnectionStrings__InstaRent_Mongo
       
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
          
        volumeMounts:
        - mountPath: /dev-cert
          name: dev-cert
        - mountPath: /app/Logs
          name: paymentlogsdata 
          subPathExpr: payment/$(POD_NAME) 
          
      imagePullSecrets:
      - name: regcred          
      volumes:
      - name: dev-cert
        secret:
          secretName: instranet-cert     
      - name: paymentlogsdata
        persistentVolumeClaim:
          claimName: irlogs        
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: ClusterIP
  selector:
    app: instarent-payment
  ports:
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
      #nodePort: 32016 # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
      #nodePort: 30016 # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)      
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-payment-deployment
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: instarent-payment-deployment
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 70
